### PR TITLE
Verify scripts/*

### PR DESCRIPTION
**Pull request by SohilZidan**
@SalimFares4 please verify by doing the following:

downloadin [articles](https://drive.google.com/file/d/1ilN9ZMmHnJErSnW47-tmO21hcvtlqiAZ/view?usp=sharing) folder inito <repo-root>/dataset
installing ol package while you are inside the repo-root: pip install -e ./
testing the nootbook: tokenization

### CODE REVIEW

**Comment by SalimFares4** [comment]
@SohilZidan 
Does not work. Need some work on directories' names. I also didn't notice any difference between (input, output).

There is no directory with the name AllSentences or at least it is not created

**Comment by SohilZidan** [comment]
> @SohilZidan Does not work. Need some work on directories' names. I also didn't notice any difference between (input, output).
> 
> There is no directory with the name AllSentences or at least it is not created

did you work on the branch reorganize? in that case you don't need any `AllSentences` folder. Nevertheless, all process prior to tokenization should be applied:
1. preprocessing generates clean_articles
2. tokenization uses clean_articles and generates tokenized_articles

**Comment by SohilZidan** [comment]
@SalimFares4 As the articles are not super, and tokenization (for now) is done using only full stop `.`, the article may be 200 words, yet one sentence.

**Comment by SalimFares4** [comment]
@SohilZidan 
Okay then, if you don't have anything else to add you can merge the pull request and close this issue

**Pull request merged**
